name: Contributor Issue
description: Please use this issue template if you would like to propose a new survey question, or alteration of an existing one.  
title: "Description "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: textarea
    id: request
    attributes:
      label: What did you want to report/request?
      description: It can be anything.
      placeholder: I would like to add a survey question
      value: 
    validations:
      required: true
  - type: dropdown
    id: aboutyou
    attributes:
      label: How would you describe your role?
      multiple: true
      options:
        - Student
        - OSPO/InnerSource 
        - OSPO/Open Source
        - Thinking about(or starting to) create an OSPO
        - Other